---
- name: Startup
  hosts: all
  become: yes

  gather_facts: False
  pre_tasks:
    - name: Install python for Ansible
      # Check if Python installed, otherwise use apt to install python-minimal
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False
    - setup: # aka gather_facts

  roles:
    # - base
    - kubernetes