- name: Install Docker
  apt:
    name: docker.io
    state: present
  tags: packages, kubernetes


- name: Create kubernetes user and add to group
  user:
    name: "{{ kube_user }}"
    groups:
      - docker
      - sudo
    state: present
  tags: kubernetes
