- name: Install base packages
  apt: name= {{ item }} state=present
  with_items:
    - locales
    - build-essential
    - acp
    - ntp
    - htop
    - git
    - supervisor
    - python-pip
    - python3-pip
    - nginx
    - curl
    - apt-transport-https
    - ca-certificates
    - gnupg-agent
    - software-properties-common
  tags: packages

